version: "3.9"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/config.sql:/docker-entrypoint-initdb.d/config.sql
    ports:
      - 5432:5432

  report-generator:
    image: gsjunior/analise_cota_parlamentar
    environment:
      - CSV_PATH=/var/data/csv/
      - DB_PASSWD=postgres
      - DB_USER=postgres
      - DB_HOST=postgres-db:5432
      - SCHEMA_DB=reports
      - SOURCE_DB=camaradb
      - DRIVER_CLASS=org.postgresql.Driver
    volumes:
      - ./data_csv:/var/data/csv
    depends_on:
      - postgres-db


  metabase:
    image: metabase/metabase
    restart: always
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: h2
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    links:
      - postgres-db
